// Formaciones compartidas entre el Lineup Builder y el Fantasy — cada
// posición es { id, x, y, label } con x/y en porcentaje sobre el campo y
// label como grupo POR/DEF/MED/DEL (para casar con la posición real del
// jugador al construir el once).
export const formations = {
  '4-3-3': [
    { id: 'GK',   x: 50, y: 88, label: 'POR' },
    { id: 'DEF1', x: 12, y: 72, label: 'DEF' },
    { id: 'DEF2', x: 34, y: 72, label: 'DEF' },
    { id: 'DEF3', x: 66, y: 72, label: 'DEF' },
    { id: 'DEF4', x: 88, y: 72, label: 'DEF' },
    { id: 'MID1', x: 22, y: 50, label: 'MED' },
    { id: 'MID2', x: 50, y: 50, label: 'MED' },
    { id: 'MID3', x: 78, y: 50, label: 'MED' },
    { id: 'FWD1', x: 18, y: 24, label: 'DEL' },
    { id: 'FWD2', x: 50, y: 24, label: 'DEL' },
    { id: 'FWD3', x: 82, y: 24, label: 'DEL' },
  ],
  '4-3-3 Ofensivo': [
    { id: 'GK',   x: 50, y: 88, label: 'POR' },
    { id: 'DEF1', x: 12, y: 72, label: 'DEF' },
    { id: 'DEF2', x: 34, y: 72, label: 'DEF' },
    { id: 'DEF3', x: 66, y: 72, label: 'DEF' },
    { id: 'DEF4', x: 88, y: 72, label: 'DEF' },
    { id: 'MID1', x: 22, y: 50, label: 'MED' },
    { id: 'MID2', x: 50, y: 42, label: 'MED' },
    { id: 'MID3', x: 78, y: 50, label: 'MED' },
    { id: 'FWD1', x: 18, y: 24, label: 'DEL' },
    { id: 'FWD2', x: 50, y: 24, label: 'DEL' },
    { id: 'FWD3', x: 82, y: 24, label: 'DEL' },
  ],
  '4-4-2': [
    { id: 'GK',   x: 50, y: 88, label: 'POR' },
    { id: 'DEF1', x: 12, y: 70, label: 'DEF' },
    { id: 'DEF2', x: 34, y: 70, label: 'DEF' },
    { id: 'DEF3', x: 66, y: 70, label: 'DEF' },
    { id: 'DEF4', x: 88, y: 70, label: 'DEF' },
    { id: 'MID1', x: 12, y: 47, label: 'MED' },
    { id: 'MID2', x: 37, y: 47, label: 'MED' },
    { id: 'MID3', x: 63, y: 47, label: 'MED' },
    { id: 'MID4', x: 88, y: 47, label: 'MED' },
    { id: 'FWD1', x: 33, y: 23, label: 'DEL' },
    { id: 'FWD2', x: 67, y: 23, label: 'DEL' },
  ],
  '4-4-2 en rombo': [
    { id: 'GK',   x: 50, y: 88, label: 'POR' },
    { id: 'DEF1', x: 12, y: 72, label: 'DEF' },
    { id: 'DEF2', x: 34, y: 72, label: 'DEF' },
    { id: 'DEF3', x: 66, y: 72, label: 'DEF' },
    { id: 'DEF4', x: 88, y: 72, label: 'DEF' },
    { id: 'MID1', x: 50, y: 60, label: 'MED' },
    { id: 'MID2', x: 20, y: 47, label: 'MED' },
    { id: 'MID3', x: 80, y: 47, label: 'MED' },
    { id: 'MID4', x: 50, y: 34, label: 'MED' },
    { id: 'FWD1', x: 33, y: 20, label: 'DEL' },
    { id: 'FWD2', x: 67, y: 20, label: 'DEL' },
  ],
  '4-2-3-1': [
    { id: 'GK',   x: 50, y: 88, label: 'POR' },
    { id: 'DEF1', x: 12, y: 73, label: 'DEF' },
    { id: 'DEF2', x: 30, y: 80, label: 'DEF' },
    { id: 'DEF3', x: 70, y: 80, label: 'DEF' },
    { id: 'DEF4', x: 88, y: 73, label: 'DEF' },
    { id: 'MID1', x: 33, y: 55, label: 'MED' },
    { id: 'MID2', x: 67, y: 55, label: 'MED' },
    { id: 'CAM1', x: 15, y: 40, label: 'MED' },
    { id: 'CAM2', x: 50, y: 44, label: 'MED' },
    { id: 'CAM3', x: 85, y: 40, label: 'MED' },
    { id: 'FWD1', x: 50, y: 20, label: 'DEL' },
  ],
  '3-4-2-1': [
    { id: 'GK',   x: 50, y: 89, label: 'POR' },
    { id: 'DEF1', x: 17, y: 72, label: 'DEF' },
    { id: 'DEF2', x: 50, y: 67, label: 'DEF' },
    { id: 'DEF3', x: 83, y: 72, label: 'DEF' },
    { id: 'MID1', x: 15, y: 50, label: 'MED' },
    { id: 'MID2', x: 33, y: 58, label: 'MED' },
    { id: 'MID3', x: 67, y: 58, label: 'MED' },
    { id: 'MID4', x: 85, y: 50, label: 'MED' },
    { id: 'CAM1', x: 33, y: 35, label: 'MED' },
    { id: 'CAM2', x: 67, y: 35, label: 'MED' },
    { id: 'FWD1', x: 50, y: 22, label: 'DEL' },
  ],
  '5-3-2': [
    { id: 'GK',   x: 50, y: 89, label: 'POR' },
    { id: 'DEF1', x: 8,  y: 72, label: 'DEF' },
    { id: 'DEF2', x: 28, y: 72, label: 'DEF' },
    { id: 'DEF3', x: 50, y: 67, label: 'DEF' },
    { id: 'DEF4', x: 72, y: 72, label: 'DEF' },
    { id: 'DEF5', x: 92, y: 72, label: 'DEF' },
    { id: 'MID1', x: 22, y: 47, label: 'MED' },
    { id: 'MID2', x: 50, y: 45, label: 'MED' },
    { id: 'MID3', x: 78, y: 47, label: 'MED' },
    { id: 'FWD1', x: 33, y: 23, label: 'DEL' },
    { id: 'FWD2', x: 67, y: 23, label: 'DEL' },
  ],
}

export const formationsList = Object.keys(formations)
